Repository spryker/docker-sdk, pull requests merged in 2019-10, with the labels that each got.

#41 SC-1985: Console command generates archives with assets
  bin/production-image.sh
  generator/src/templates/deploy.bash.twig
Labels: feature

#39 SC-2026: Snapshot register leads to error
  context/elasticsearch/elasticsearch.yml
  generator/src/templates/service/elastic.yml.twig
Labels: bug, ready-for-release

#38 SC-2092: Swagger UI
  generator/index.php
  generator/src/templates/env/cli/store.env.twig
  generator/src/templates/env/swagger/swagger-ui.env.twig
  generator/src/templates/nginx/http/glue.server.conf.twig
  generator/src/templates/nginx/http/rpc.server.conf.twig
  generator/src/templates/nginx/http/swagger-ui.server.conf.twig
  generator/src/templates/service/swagger-ui.yml.twig
  images/swagger/Dockerfile
  images/swagger/swagger-entrypoint.sh
Labels: improvement, ready-for-release

#44 SC-2256: Adjust Travis not to generate assets
  generator/src/templates/deploy.bash.twig
Labels: improvement, ready-for-release

#46 SC-2092: Demo mode, swagger file generation
  images/swagger/Dockerfile
Labels: ready-for-release
