Repository spryker/docker-sdk, pull requests merged in 2019-07, with the labels that each got.

#15 [SC-1728] [SC-1729] [SC-1732]
  .gitignore
  generator/index.php
  generator/src/templates/application-volumes.yml.twig
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.test.yml.twig
  generator/src/templates/docker-compose.yml.twig
  generator/src/templates/env/cli/store.env.twig
  generator/src/templates/nginx/http/rpc.server.conf.twig
Labels: bug, request review

#16 SC-1811: Providing arguments form bash to api test console command
  generator/src/templates/deploy.bash.twig
Labels: bug

#17 SC-1815: Docker SDK: Zed acceptance tests fail
  generator/index.php
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.test.xdebug.yml.twig
  generator/src/templates/env/cli/store.env.twig
  generator/src/templates/env/cli/testing.env.twig
Labels: bug, ready for release
