Repository spryker/docker-sdk, pull requests merged in 2019-09, with the labels that each got.

#28 SC-1936: Provide an access to Redis on Dev env
  .travis.yml
  generator/src/templates/nginx/tcp/redis.server.conf.twig
Labels: improvement, merge-only, ready-for-release

#27 SC-1917: Update help
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.test.xdebug.yml.twig
  generator/src/templates/docker-compose.test.yml.twig
Labels: bug, ready-for-release

#23 SC-1874: Docker: PHPStorm does not determinate Spryker debug session
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.test.xdebug.yml.twig
  generator/src/templates/docker-compose.xdebug.yml.twig
  generator/src/templates/env/cli/store.env.twig
  generator/src/templates/env/cli/testing.env.twig
Labels: bug, ready-for-release

#31 SC-1877: Docker CE cannot be detected properly
  bin/check-docker.sh
Labels: bug, ready-for-release

#29 SC-1923: Implemented jobs for travis(check boot and syntax)
  .travis.yml
  ci/check_bash_syntax.sh
  ci/check_boot.sh
  ci/deploy.dev.yml
  ci/deploy.yml
Labels: improvement, ready-for-release

#37 SC-2094: Outdated docker compose
  bin/boot-deployment.sh
  bin/check-docker-compose.sh
  ci/check_boot.sh
  generator/src/templates/deploy.bash.twig
Labels: bug, ready-for-release

#34 SC-1870: Adding TCP socket relay for Jenkins to be used for accessing…
  generator/src/templates/deploy.bash.twig
  generator/src/templates/service/jenkins.yml.twig
Labels: bug, ready-for-release
