Repository spryker/docker-sdk, pull requests merged in 2020-01, with the labels that each got.

#61 SC-2639: "No such file or directory" error - during moving assets from temp directory
  bin/assets/baked.sh
Labels: QA, bug

#59 SC-2640: Generation assets doesn't work if the destination folder wasn't created before generation
  bin/assets/baked.sh
  bin/export-helper.sh
Labels: QA, bug

#57 SC-2258: Port 80 is locked
  generator/index.php
  generator/src/templates/docker-compose.yml.twig
Labels: bug, ready-for-release

#56 SC-2612: Add "images" word in the description of the command: docker/sdk help
  generator/src/templates/deploy.bash.twig
Labels: bug, ready-for-release

#58 SC-2085: "docker/sdk boot" lead to error if docker-machine are using on Linux env
  bin/boot-deployment.sh
  bin/check-docker-machine.sh
Labels: bug, ready-for-release

#63 Create assets volume
  generator/src/templates/deploy.bash.twig
Labels: bug, ready-for-release

#62 SC-2614: Dev mode (docker-sync) doesn`t work with ES6
  bin/mount/docker-sync.sh
  generator/src/templates/deploy.bash.twig
Labels: bug, ready-for-release

#64 SC-2733: Controlling --no-dev option
  bin/build/mount.sh
  bin/images/baked.sh
  bin/images/mount.sh
  generator/src/templates/deploy.bash.twig
  images/base_app/Dockerfile
Labels: improvement, prio, ready-for-release
