Repository spryker/docker-sdk, pull requests merged in 2020-07, with the labels that each got.

#121 SC-3446: DRAFT. NR, Blackfire and Tideways are supported
  generator/src/templates/application/glue.yml.twig
  generator/src/templates/application/yves.yml.twig
  generator/src/templates/application/zed.yml.twig
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.yml.twig
  generator/src/templates/env/common.env.twig
  generator/src/templates/service/tideways/default/tideways.yml.twig
  generator/src/templates/service/tideways/tideways.bash.twig
  images/tideways/Dockerfile
Labels: feature, ready-for-release

#123 SC-4036: Second level domain for teraform generation
  generator/index.php
Labels: improvement, ready-for-release

#125 SC-3990: Make port to fastcgi application configurable
  generator/src/templates/nginx/conf.d/frontend.default.conf.twig
  generator/src/templates/nginx/entrypoint.sh.twig
Labels: improvement, merge-only, ready-for-release

#104 SC-2027: Command "console storage:redis:export " lead to - Could not export rdb file
  images/common/cli/Dockerfile
Labels: bug, ready-for-release

#126 Added template for ES7
  generator/src/templates/service/elastic/7.6/elastic.yml.twig
Labels: feature, ready-for-release

#127 SC-4086: Docker SDK: Testing mode leads to fatal error on Yves
  generator/index.php
  generator/src/templates/docker-compose.test.yml.twig
  images/common/application/Dockerfile.twig
  images/mount/application/Dockerfile
Labels: bug, ready-for-release
