Repository spryker/docker-sdk, pull requests merged in 2020-02, with the labels that each got.

#67 SC-2840: Docker SDK: Multiple issues on Windows
  bin/boot-deployment.sh
  bin/build/mount.sh
  generator/src/templates/application-volumes.yml.twig
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-sync.yml.twig
Labels: bug, ready-for-release

#69 SC-2855: Support kibana 6
  README.md
  generator/src/templates/service/kibana/6.8/kibana.yml.twig
Labels: improvement, ready-for-release

#70 SC-2841: Implement autoload caching
  bin/build/mount.sh
  bin/mount/nfs.sh
  generator/index.php
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.yml.twig
  generator/src/templates/env/common.env.twig
Labels: feature, request-review

#66 SC-2566: ".ssh/known_hosts" should be updated with ssh github.com command
  bin/boot-deployment.sh
  bin/images/baked.sh
  bin/images/mount.sh
  generator/index.php
  generator/src/templates/deploy.bash.twig
  images/base_app/Dockerfile
  images/base_dev/Dockerfile
Labels: bug, ready-for-release

#65 SC-2525: Error during run app in dev mode if MySql was set 3306 port in deploy.dev.yml
  generator/src/templates/service/mysql/5.7/mysql.yml.twig
Labels: bug, ready-for-release
