Repository spryker/docker-sdk, pull requests merged in 2020-06, with the labels that each got.

#110 SC-3061: PostgreSQL 10/11/12 is supported
  README.md
  generator/src/templates/service/postgres/10/postgres.yml.twig
  generator/src/templates/service/postgres/11/postgres.yml.twig
  generator/src/templates/service/postgres/12/postgres.yml.twig
Labels: feature, improvement, ready-for-release

#106 SC-2294: RedisGui
  generator/index.php
  generator/src/templates/docker-compose.yml.twig
  generator/src/templates/nginx/http/redis-commander.server.conf.twig
  generator/src/templates/service/redis-commander/default/redis-commander.yml.twig
Labels: improvement, ready-for-release

#102 SC-2569: spryker_b2c_dev_broker_1 has unhealthy status during "docker/sdk up"
  generator/src/templates/deploy.bash.twig
Labels: bug, ready-for-release

#105 SC-2661: Blackfire && NewRelic Support
  README.md
  bin/build/baked.sh
  bin/build/mount.sh
  bin/images/baked.sh
  bin/images/main.sh
  bin/images/mount.sh
  generator/index.php
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.yml.twig
  generator/src/templates/env/common.env.twig
  generator/src/templates/images/main/Dockerfile.twig
  generator/src/templates/php/conf.d/99-from-deploy-yaml-php.ini.twig
  generator/src/templates/service/blackfire/default/blackfire.yml.twig
  generator/src/templates/service/blackfire/latest/blackfire.yml.twig
  images/cli/demo/Dockerfile
  images/cli/dev/Dockerfile
Labels: improvement, ready-for-release

#112 SC-3085: MariaDB v10.2-4 is supported
  README.md
  generator/src/templates/service/mysql/mariadb-10.2/mysql.yml.twig
  generator/src/templates/service/mysql/mariadb-10.3/mysql.yml.twig
  generator/src/templates/service/mysql/mariadb-10.4/mysql.yml.twig
Labels: feature, improvement, ready-for-release

#114 SC-3131: Generate apple valid cert
  generator/openssl/v3.ext
Labels: bug, ready-for-release

#103 SC-2979: Installation happens before project's data is copied
  images/base_app/Dockerfile
Labels: bug, ready-for-release

#116 SC-3127: Document how to use TLS locally
  generator/index.php
  generator/openssl/generate.sh
Labels: bug, ready-for-release

#120 SC-3694: docker/sdk export assets does not work properly
  bin/sdk/assets/baked.sh
  generator/index.php
  generator/src/templates/deploy.bash.twig
Labels: bug
