Repository spryker/docker-sdk, pull requests merged in 2020-09, with the labels that each got.

#144 SC-4827: Fixed wrong prompt in CLI on debian-based image
  bin/standalone/cli.sh
Labels: bug, ready-for-release

#143 Issue 140: Updated vulnerable dependency (bl)
  context/dashboard/package-lock.json
  context/dashboard/package.json
Labels: bug, prio, ready-for-release

#141 SC-4807: Added possibility to set CORS allow origin value via deploy.yml
  generator/index.php
  generator/src/templates/nginx/http/glue.server.conf.twig
Labels: improvement, ready-for-release

#135 SC-4606: Adding the possibility to set sender email/name via deploy.yml.
  ci/deploy.dev.yml
  ci/deploy.yml
  generator/src/templates/env/application/glue.env.twig
  generator/src/templates/env/application/yves.env.twig
  generator/src/templates/env/application/zed.env.twig
  generator/src/templates/env/cli/store.env.twig
  generator/src/templates/env/mail/mail.env.twig
  generator/src/templates/env/scheduler/jenkins.env.twig
  generator/src/templates/nginx/http/glue.server.conf.twig
  generator/src/templates/nginx/http/yves.server.conf.twig
  generator/src/templates/nginx/http/zed.server.conf.twig
  generator/src/templates/terraform/application/glue.tf.twig
  generator/src/templates/terraform/application/yves.tf.twig
  generator/src/templates/terraform/application/zed.tf.twig
  generator/src/templates/terraform/mail/mail.tf.twig
Labels: improvement, ready-for-release

#145 SC-4820: Fixed extra redirection when using redirect attribute in SSL mode
  generator/composer.json
  generator/composer.lock
  generator/index.php
  generator/src/templates/nginx/http/static.server.conf.twig
Labels: bug, ready-for-release

#142 SC-4805: Added possibility to disable xdebug images and modes
  bin/command/deploy.sh
  bin/sdk/compose.sh
  bin/sdk/images/common.sh
  bin/standalone/cli.sh
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.yml.twig
  generator/src/templates/nginx/conf.d/debug.default.conf.twig
  generator/src/templates/nginx/conf.d/gateway.default.conf.twig
  images/common/dashboard/Dockerfile
  images/common/services/tideways/Dockerfile
  images/debug/application/Dockerfile
  images/debug/cli/Dockerfile
  images/debug/frontend/Dockerfile
Labels: improvement, ready-for-release

#139 SC-4745: Added keys and token generator for auth purposes
  generator/index.php
  generator/src/templates/env/common.env.twig
  generator/src/templates/terraform/broker/rabbitmq.tf.twig
  generator/src/templates/terraform/database/mysql.tf.twig
  generator/src/templates/terraform/database/postgres.tf.twig
  generator/src/templates/terraform/environment.common.tf.twig
  generator/src/templates/terraform/secrets.sdk.auto.tfvars.twig
Labels: improvement, request-review

#150 BC check for public B2C and B2B demoshops
  .travis.yml
Labels: improvement

#148 SC-4745: Added keys and token generator for auth purposes
  generator/index.php
  generator/src/templates/env/common.env.twig
  generator/src/templates/terraform/broker/rabbitmq.tf.twig
  generator/src/templates/terraform/database/mysql.tf.twig
  generator/src/templates/terraform/database/postgres.tf.twig
  generator/src/templates/terraform/environment.common.tf.twig
  generator/src/templates/terraform/secrets.sdk.auto.tfvars.twig
Labels: improvement, ready-for-release

#147 TE-7283: Replaced PhantomJS with Chromedriver for testing mode
  generator/src/templates/docker-compose.test.yml.twig
  generator/src/templates/docker-compose.yml.twig
  generator/src/templates/env/cli/testing.env.twig
  generator/src/templates/service/chromedriver/default/chromedriver.yml.twig
  generator/src/templates/service/phantomjs/default/phantomjs.yml.twig
Labels: improvement, request-AA-review, request-review

#151 SC-4925: Fixed SSL self-signed certificate issue in non-debug mode
  bin/sdk/images/common.sh
  images/baked/application/Dockerfile
  images/common/application-local/Dockerfile
  images/debug/application/Dockerfile
  images/debug/cli/Dockerfile
Labels: bug, ready-for-release

#138 SC-4434: Added SSH agent forwarding for building and CLI container.
  .github/ISSUE_TEMPLATE/feature.template.md
  .travis.yml
  bin/command/build/baked/export.sh
  bin/environment/composer.sh
  bin/framework.sh
  bin/installer/vcs.sh
  bin/registry/trap.sh
  bin/sdk/compose.sh
  bin/sdk/data/demo.sh
  bin/sdk/images/baked.sh
  bin/sdk/images/common.sh
  bin/sdk/images/mount.sh
  ci/tests.sh
  ci/tests/registry/trap/chech-remove.case.sh
  ci/tests/registry/trap/check-edge.case.sh
  ci/tests/registry/trap/check-on-exit.case.sh
  ci/tests/registry/trap/check-release.case.sh
  ci/tests/registry/trap/trap.test.sh
  context/ssh/ssh-agent.mock
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.yml.twig
  generator/src/templates/service/jenkins/2.176/jenkins.yml.twig
  images/baked/application/Dockerfile
  images/baked/cli/Dockerfile
  images/common/cli/Dockerfile
Labels: improvement, ready-for-release
