Repository spryker/docker-sdk, pull requests merged in 2020-03, with the labels that each got.

#73 SC-2274: Can't stop docker containers
  generator/src/templates/deploy.bash.twig
Labels: bug, ready-for-release

#74 SC-2895: Docker images have Debian as base distro
  bin/assets/baked.sh
  images/builder_assets/Dockerfile
  images/cli/demo/Dockerfile
  images/cli/dev/Dockerfile
Labels: feature

#78 SC-2951: Clearing `opcache` under `root` in order to avoid permission…
  images/base_app/Dockerfile
Labels: bug, ready-for-release

#75 SC-2894: Docker images have Debian as base distro
  bin/assets/baked.sh
  images/builder_assets/Dockerfile
  images/cli/demo/Dockerfile
  images/cli/dev/Dockerfile
Labels: feature, improvement, ready-for-release

#81 SC-2803: Assets not ready for production
  .dockerignore.default
  bin/assets/baked.sh
  bin/assets/tar-builder.sh
  bin/export-helper.sh
  bin/images/baked.sh
  bin/images/image-builder-helper.sh
  bin/images/mount.sh
  generator/src/templates/deploy.bash.twig
  images/base_app/Dockerfile
  images/builder_assets/Dockerfile
  sdk
Labels: bug, prio, ready-for-release
