Repository spryker/docker-sdk, pull requests merged in 2020-10, with the labels that each got.

#154 SC-5142: Introduced `max-request-body-size` to be set per application
  generator/index.php
  generator/src/templates/nginx/conf.d/debug.default.conf.twig
  generator/src/templates/nginx/conf.d/frontend.default.conf.twig
  generator/src/templates/nginx/conf.d/gateway.default.conf.twig
  generator/src/templates/nginx/http/gateway/server.conf.twig
  generator/src/templates/nginx/vhost.d/glue.default.conf.twig
  generator/src/templates/nginx/vhost.d/yves.default.conf.twig
  generator/src/templates/nginx/vhost.d/zed.default.conf.twig
Labels: improvement, ready-for-release

#153 TE-7283: Added support of Chromedriver for E2E testing
  README.md
  bin/sdk/compose.sh
  ci/check_boot.sh
  context/nginx/dummy/scheduler.conf
  generator/index.php
  generator/src/templates/application/glue.yml.twig
  generator/src/templates/application/yves.yml.twig
  generator/src/templates/application/zed.yml.twig
  generator/src/templates/deploy.bash.twig
  generator/src/templates/docker-compose.yml.twig
  generator/src/templates/env/cli/testing.env.twig
  generator/src/templates/env/testing.env.twig
  generator/src/templates/env/webdriver/chromedriver.env.twig
  generator/src/templates/env/webdriver/phantomjs.env.twig
  generator/src/templates/nginx/conf.d/gateway.default.conf.twig
  generator/src/templates/nginx/http/gateway/jenkins.server.conf.twig
  generator/src/templates/nginx/http/gateway/server.conf.twig
  generator/src/templates/service/chromedriver/default/chromedriver.yml.twig
  generator/src/templates/service/phantomjs/default/phantomjs.yml.twig
  images/common/application/Dockerfile.twig
Labels: improvement, no-squash, ready-for-release

#137 SC-4713: Introduced the URL to get OpenAPI schema for all Glue endpoints.
  bin/service/scheduler/jenkins.sh
  bin/standalone/cli-rpc.js
  context/jenkins/spryker.sh
  generator/index.php
  generator/src/templates/env/swagger/swagger-ui.env.twig
  generator/src/templates/nginx/conf.d/gateway.default.conf.twig
  generator/src/templates/nginx/http/gateway/glue.server.conf.twig
  generator/src/templates/nginx/http/gateway/yves.server.conf.twig
  generator/src/templates/nginx/http/gateway/zed.server.conf.twig
  generator/src/templates/service/swagger-ui/v3.24/swagger-ui.yml.twig
  images/swagger/Dockerfile
  images/swagger/swagger-entrypoint.sh
Labels: bug, ready-for-release
