Repository spryker/docker-sdk, pull requests merged in 2021-06, with the labels that each got.

#204 SC-6516: Merchant Portal
  docs/06-installation/02-installation-guides/01-choosing-an-installation-mode.md
  docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md
  docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md
  docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md
  docs/09-troubleshooting.md
  docs/99-deploy.file.reference.v1.md
  generator/index.php
  generator/src/templates/application/merchant-portal.yml.twig
  generator/src/templates/env/application/merchant-portal.env.twig
  generator/src/templates/nginx/http/gateway/merchant-portal.server.conf.twig
  generator/src/templates/nginx/http/merchant-portal.server.conf.twig
  generator/src/templates/nginx/vhost.d/merchant-portal.default.conf.twig
  generator/src/templates/terraform/application/merchant-portal.tf.twig
Labels: improvement, ready-for-release

#193 SC-6257: Gateway and BackOffice application
  docs/06-installation/02-installation-guides/01-choosing-an-installation-mode.md
  docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md
  docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md
  docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md
  docs/09-troubleshooting.md
  docs/10-configuration-reference.md
  docs/99-deploy.file.reference.v1.md
  generator/index.php
  generator/src/templates/application/backend-gateway.yml.twig
  generator/src/templates/application/backoffice.yml.twig
  generator/src/templates/env/application/backend-gateway.env.twig
  generator/src/templates/env/application/backoffice.env.twig
  generator/src/templates/env/cli/store.env.twig
  generator/src/templates/env/cli/testing.env.twig
  generator/src/templates/nginx/conf.d/debug.default.conf.twig
  generator/src/templates/nginx/conf.d/frontend.default.conf.twig
  generator/src/templates/nginx/http/backend-gateway.server.conf.twig
  generator/src/templates/nginx/http/backoffice.server.conf.twig
  generator/src/templates/nginx/http/gateway/backend-gateway.server.conf.twig
  generator/src/templates/nginx/http/gateway/backoffice.server.conf.twig
  generator/src/templates/nginx/vhost.d/backend-gateway.default.conf.twig
  generator/src/templates/nginx/vhost.d/backoffice.default.conf.twig
  generator/src/templates/terraform/application/backend-gateway.tf.twig
  generator/src/templates/terraform/application/backoffice.tf.twig
  generator/src/templates/terraform/store.env.twig
Labels: improvement, ready-for-release

#214 [SC-7065]: Documentation adjustments. Installation section
  docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md
  docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md
  docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md
Labels: bug, ready-for-release

#217 Fix minor bugs 99-deploy.file.reference.v1.md
  docs/99-deploy.file.reference.v1.md
Labels: documentation

#213 SC-7186: EntryPoint has incorect case
  generator/index.php
Labels: bug
