Repository spryker/docker-sdk, pull requests merged in 2021-03, with the labels that each got.

#191 Updated debugging configuration instructions
  docs/02-development/05-configuring-debugging.md
Labels: bug, documentation, ready-for-release

#199 AC-1133: Documentation: Separated windows installation instructions
  docs/01-quick-start-guide.md
  docs/06-installation/01-installation-prerequisites/01-installing-docker-prerequisites-on-macos.md
  docs/06-installation/01-installation-prerequisites/02-installing-docker-prerequisites-on-linux.md
  docs/06-installation/01-installation-prerequisites/03-installing-docker-prerequisites-on-windows.md
  docs/06-installation/02-installation-guides/01-choosing-an-installation-mode.md
  docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md
  docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md
  docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md
  docs/06-installation/02-installation-guides/07-running-production.md
Labels: documentation, improvement

#197 MariaDB 10.5 support
  README.md
  generator/src/templates/service/mysql/mariadb-10.5/mysql.yml.twig
Labels: improvement, ready-for-release

#177 SC-6081: Check docker sdk boot
  docs/05-configuring-access-to-private-repositories.md
  generator/index.php
Labels: bug, ready-for-release
