Repository spryker/docker-sdk, pull requests merged in 2021-01, with the labels that each got.

#166 SC-5791: Check behavior of json_encode in oauth token generation script(docker-sdk)
  generator/index.php
Labels: bug, ready-for-release

#160 SC-5307: Import existing prerequisites and installation docs
  docs/06-installation/01-installation-prerequisites/01-installing-docker-prerequisites-on-macos.md
  docs/06-installation/01-installation-prerequisites/02-installing-docker-prerequisites-on-linux.md
  docs/06-installation/01-installation-prerequisites/03-installing-docker-prerequisites-on-windows.md
  docs/06-installation/02-installation-guides/01-choosing-an-installation-mode.md
  docs/06-installation/02-installation-guides/02-installing-in-demo-mode.md
  docs/06-installation/02-installation-guides/02-installing-in-development-mode.md
  docs/06-installation/02-installation-guides/03-integrating-docker-into-existing-projects.md
  docs/06-installation/02-installation-guides/04-running-production.md
  docs/06-installation/03-installation.md
Labels: documentation

#165 SC-5361: Running tests
  docs/02-development-usage/06-running-tests.md
Labels: documentation

#167 SC-5355:04-debugging.md
  docs/02-development-usage/05-configuring-debugging.md
Labels: documentation

#172 Documentation (highest and high priority docs)
  docs/01-quick-start-guide.md
  docs/02-development-usage/01-choosing-a-mount-mode.md
  docs/02-development-usage/05-configuring-debugging.md
  docs/02-development-usage/06-running-tests.md
  docs/02-development-usage/07-configuring-a-mount-mode.md
  docs/04-choosing-a-docker-sdk-version.md
  docs/05-configuring-access-to-private-repositories.md
  docs/06-configuring-services.md
  docs/06-installation/01-installation-prerequisites/01-installing-docker-prerequisites-on-macos.md
  docs/06-installation/01-installation-prerequisites/02-installing-docker-prerequisites-on-linux.md
  docs/06-installation/01-installation-prerequisites/03-installing-docker-prerequisites-on-windows.md
  docs/06-installation/02-installation-guides/01-choosing-an-installation-mode.md
  docs/06-installation/02-installation-guides/02-installing-in-development-mode.md
  docs/06-installation/02-installation-guides/03-installing-in-demo-mode.md
  docs/06-installation/02-installation-guides/04-integrating-the-docker-sdk-into-existing-projects.md
  docs/06-installation/02-installation-guides/05-running-production.md
  docs/09-troubleshooting.md
  docs/10-configuration-reference.md
  docs/99-deploy.file.reference.v1.md
Labels: documentation, improvement, ready-for-release

#174 Replace tabs with spaces in the deploy file reference
  docs/06-installation/02-installation-guides/03-installing-in-demo-mode.md
  docs/99-deploy.file.reference.v1.md
Labels: documentation, improvement, ready-for-release

#176 Add WSL1 configuration prerequisites
  docs/02-development/01-choosing-a-mount-mode.md
  docs/02-development/05-configuring-debugging.md
  docs/02-development/06-running-tests.md
  docs/02-development/07-configuring-a-mount-mode.md
  docs/06-installation/01-installation-prerequisites/03-installing-docker-prerequisites-on-windows.md
  docs/99-deploy.file.reference.v1.md
Labels: documentation, improvement
