Repository spryker/docker-sdk, pull requests merged in 2021-02, with the labels that each got.

#168 SC-5877: ES Index prefix
  generator/src/templates/env/application/glue.env.twig
  generator/src/templates/env/application/yves.env.twig
  generator/src/templates/env/application/zed.env.twig
  generator/src/templates/env/search/elastic.env.twig
  generator/src/templates/terraform/application/glue.tf.twig
  generator/src/templates/terraform/application/yves.tf.twig
  generator/src/templates/terraform/application/zed.tf.twig
  generator/src/templates/terraform/search/elastic.tf.twig
Labels: improvement, ready-for-release

#179 Stick NPM to 6 version for BC
  images/common/cli/Dockerfile
Labels: ready-for-release

#180 SC-6114: Fixed Xdebug v3 debugging mode.
  context/php/debug/etc/php/debug.conf.d/69-xdebug.ini
  docs/02-development/05-configuring-debugging.md
Labels: bug, ready-for-release
