Repository spryker/docker-sdk, pull requests merged in 2021-05, with the labels that each got.

#205 SC-6662: Fixed permission error for frontend-related assets.
  images/baked/assets/Dockerfile
Labels: bug, ready-for-release

#202 AC-1137: Unify readme files
  README.md
  docs/01-quick-start-guide.md
  docs/02-development/01-choosing-a-mount-mode.md
  docs/02-development/05-configuring-debugging.md
  docs/02-development/06-running-tests.md
  docs/02-development/07-configuring-a-mount-mode.md
  docs/04-choosing-a-docker-sdk-version.md
  docs/05-configuring-access-to-private-repositories.md
  docs/06-configuring-services.md
  docs/06-installation/01-installation-prerequisites/01-installing-docker-prerequisites-on-macos.md
  docs/06-installation/01-installation-prerequisites/02-installing-docker-prerequisites-on-linux.md
  docs/06-installation/01-installation-prerequisites/03-installing-docker-prerequisites-on-windows.md
  docs/06-installation/02-installation-guides/01-choosing-an-installation-mode.md
  docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md
  docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md
  docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md
  docs/06-installation/02-installation-guides/07-running-production.md
  docs/09-troubleshooting.md
  docs/10-configuration-reference.md
  docs/99-deploy.file.reference.v1.md
Labels: documentation

#208 SC-6521: Introduce a new pipeline image
  bin/sdk/images/common.sh
Labels: improvement, ready-for-release

#207 SC-6518: Define PHP worker per application
  context/php/debug/etc/debug.php-fpm.d/worker.conf
  context/php/php-fpm.d/worker.conf
  docs/99-deploy.file.reference.v1.md
  generator/src/templates/env/application/glue.env.twig
  generator/src/templates/env/application/yves.env.twig
  generator/src/templates/env/application/zed.env.twig
  generator/src/templates/env/pm/php-fpm.env.twig
  generator/src/templates/terraform/application/glue.tf.twig
  generator/src/templates/terraform/application/yves.tf.twig
  generator/src/templates/terraform/application/zed.tf.twig
  generator/src/templates/terraform/pm/php-fpm.tf.twig
  images/common/application/Dockerfile.twig
  images/debug/application/Dockerfile
Labels: improvement, ready-for-release
