Repository spryker/docker-sdk, pull requests merged in 2022-10, with the labels that each got.

#360 [SC-10419]: ECR push image with the latest tag.
  bin/sdk/images/baked/ecr.sh
Labels: bug, ready-for-release

#372 Fix: References
  docs/01-quick-start-guide.md
  docs/02-development/01-choosing-a-mount-mode.md
  docs/02-development/06-running-tests.md
  docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md
  docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md
  docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md
  docs/07-deploy-file/02-deploy.file.reference.v1.md
  docs/09-troubleshooting.md
Labels: documentation

#377 Update link to deploy file
  README.md
Labels: documentation

#375 [SC-10005] Update Jenkins version.
  images/common/services/jenkins/export/Dockerfile
Labels: ready-for-release, security

#378 SC-11080 Change spryker-sdk to docker-sdk on the spryker.local page
  context/dashboard/views/index.pug
Labels: bug, ready-for-release

#351 SC-8908: Deploy file validation. OR condition
  generator/deploy-file-generator/config/validation.yml
  generator/deploy-file-generator/src/Validator/DeployFileValidatorFactory.php
  generator/deploy-file-generator/src/Validator/Rule/OrRule.php
  generator/deploy-file-generator/templates/environment/ci/assets.deploy.template.yml
Labels: bug, ready-for-release

#341 SC-5621: Makes platform detection for WSL2 case-insensitive
  bin/platform.sh
Labels: bug, ready-for-release
