Repository spryker/docker-sdk, pull requests merged in 2022-08, with the labels that each got.

#310 Pipeline optimisation. Jenkins image.
  bin/command/build/baked/export.sh
  bin/sdk/images/baked/ecr.sh
  bin/sdk/images/common.sh
  context/jenkins/export/entrypoint.sh
  context/jenkins/export/jenkins.docker.xml.twig
  context/jenkins/export/jenkins.model.JenkinsLocationConfiguration.xml
  images/common/services/jenkins/export/Dockerfile
Labels: improvement, ready-for-release

#346 RN-286: fix log cuts for AWS CloudWatch at 1024 chars
  context/php/php-fpm.d/worker.conf
Labels: bug, ready-for-release

#348 SC-10167: Typo in logo
  bin/standalone/logo/spryker-cli.sh
  bin/standalone/logo/spryker-sdk.sh
Labels: bug
