Repository spryker/docker-sdk, pull requests merged in 2022-12, with the labels that each got.

#352 SC-9864: Add xhprof extension into the php docker containers only for dev environment
  docs/07-deploy-file/02-deploy.file.reference.v1.md
Labels: improvement, ready-for-release

#399 SC-11505: Docker SDK: unable to run browser tests against Zed locally
  docs/06-configuring-services.md
Labels: bug, ready-for-release

#362 SC-10027: Upgrade Redis to version 6.2
  README.md
  generator/deploy-file-generator/templates/environment/ci/services.deploy.template.yml
  generator/deploy-file-generator/templates/environment/demo/services.deploy.template.yml
  generator/deploy-file-generator/templates/environment/dev/services.deploy.template.yml
  generator/src/templates/service/redis/6.2/redis.yml.twig
Labels: improvement, ready-for-release

#366 SC-10376: Maintenance mode
  bin/sdk/images/common.sh
  docs/07-deploy-file/02-deploy.file.reference.v1.md
  generator/src/templates/deploy.bash.twig
  generator/src/templates/nginx/entrypoint.sh.twig
  generator/src/templates/nginx/http/application.server.conf.twig
  generator/src/templates/nginx/http/error.conf.twig
  generator/src/templates/terraform/secrets.sdk.auto.tfvars.twig
  images/common/frontend/Dockerfile
Labels: improvement, ready-for-release

#403 SDK-1583: Fix typo in console output
  bin/command/install/install.sh
Labels: bug, ready-for-release, merge-only
