Repository spryker/docker-sdk, pull requests merged in 2022-03, with the labels that each got.

#269 SC-8405: Introduced Nginx header for set up client request header size
  generator/src/templates/nginx/conf.d/frontend.default.conf.twig
  generator/src/templates/nginx/conf.d/gateway.default.conf.twig
Labels: ready-for-release, QA Done

#291 SC-8815: Added missed PHP-FPM configuration
  generator/src/templates/env/application/backend-gateway.env.twig
  generator/src/templates/env/application/backoffice.env.twig
  generator/src/templates/env/application/merchant-portal.env.twig
  generator/src/templates/terraform/application/backend-gateway.tf.twig
  generator/src/templates/terraform/application/backoffice.tf.twig
  generator/src/templates/terraform/application/merchant-portal.tf.twig
Labels: bug, ready-for-release

#288 SC-8611: Dynamic parameters filter
  docs/07-deploy-file/01-deploy-file.md
  docs/07-deploy-file/03-deploy-file-inheritance-common-use-cases.md
  generator/deploy-file-generator/src/DeployFileGeneratorFactory.php
  generator/deploy-file-generator/src/Exception/ParameterFilterNotExistException.php
  generator/deploy-file-generator/src/ParameterFilter/Filters/LowerCaseParameterFilter.php
  generator/deploy-file-generator/src/ParameterFilter/Filters/UpperCaseParameterFilter.php
  generator/deploy-file-generator/src/ParameterFilter/ParameterFilterInterface.php
  generator/deploy-file-generator/src/ParametersResolver/Resolvers/AbstractAnnotationParameterResolver.php
  generator/deploy-file-generator/tests/unit/DeployFileGeneratorTest/ParametersResolver/Resolvers/PercentAnnotationParameterResolverTest.php
Labels: improvement, ready-for-release, QA Done

#295 SC-7329: Provide environment variable with the list of active stores
  generator/src/templates/env/common.env.twig
  generator/src/templates/terraform/environment.common.tf.twig
  generator/src/templates/terraform/store.env.twig
Labels: improvement, ready-for-release

#297 SCO-33908: Assets location allow all
  generator/src/templates/nginx/http/static.conf.twig
Labels: bug, ready-for-release

#298 SC-8896: Fix dependency alerts
  context/dashboard/package-lock.json
  context/dashboard/package.json
Labels: ready-for-release

#299 SC-8896: Fix dependency alerts
  context/dashboard/package-lock.json
  context/dashboard/package.json
Labels: ready-for-release

#294 SC-8863: Endpoints with .localhost do not require update of /etc/hosts
  docs/06-configuring-services.md
  docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
  generator/index.php
Labels: improvement, ready-for-release
