Repository spryker/docker-sdk, pull requests merged in 2022-11, with the labels that each got.

#381 SC-11155 GitHub Action - service cli is not running container
  bin/service/database/postgres.sh
Labels: bug, ready-for-release

#384 SC-11036 Key sections is not explained for installation recipes
  docs/07-deploy-file/04-installation-recipes-of-deployment-pipelines.md
Labels: documentation, ready-for-release

#386 SC-11367: FE_HOST and FE_PORT are absent in GLUE_STOREFRONT
  generator/src/templates/nginx/http/glue-storefront.server.conf.twig
Labels: bug, ready-for-release

#389 Hotfix. Debian. CI
  bin/command/install/bootstrap.sh
  generator/index.php
Labels: bug, ready-for-release, prio

#393 SC-11365 On Linux systems docker-compose is not found when docker com…
  bin/environment/docker-compose.sh
  bin/sdk/compose.sh
Labels: bug, ready-for-release

#395 SC-11653: Dynamic secrets for product configurator
  generator/index.php
Labels: ready-for-release
