Repository spryker/docker-sdk, pull requests merged in 2022-09, with the labels that each got.

#359 SC-10114: NPM library is incompatible with Docker on Mac with Apple chip
  images/common/cli/Dockerfile
Labels: bug

#350 Adjust generator with check of missed application
  generator/index.php
Labels: bug, ready-for-release

#357 SC-9556: Support PHP8.1 compatibility
  docs/09-troubleshooting.md
  images/common/cli/Dockerfile
Labels: improvement, ready-for-release

#361 [Docs] Minimum requirements adjustments
  docs/06-installation/01-installation-prerequisites/01-installing-docker-prerequisites-on-macos.md
  docs/06-installation/01-installation-prerequisites/02-installing-docker-prerequisites-on-linux.md
  docs/06-installation/01-installation-prerequisites/03-installing-docker-prerequisites-on-windows.md
  docs/06-installation/02-installation-guides/02-installing-in-development-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/03-installing-in-development-mode-on-windows.md
  docs/06-installation/02-installation-guides/04-installing-in-demo-mode-on-macos-and-linux.md
  docs/06-installation/02-installation-guides/05-installing-in-demo-mode-on-windows.md
  docs/06-installation/02-installation-guides/06-integrating-the-docker-sdk-into-existing-projects.md
Labels: tw-review
