Repository spryker/docker-sdk, pull requests merged in 2022-07, with the labels that each got.

#251 Allow creating job command without data escaping.
  context/jenkins/jenkins.docker.xml.twig
Labels: bug, ready-for-release

#330 SC-9474: Wrong host:port provision into Nginx configs from deploy file
  generator/src/templates/nginx/http/backend-gateway.server.conf.twig
  generator/src/templates/nginx/http/backoffice.server.conf.twig
  generator/src/templates/nginx/http/glue-backend.server.conf.twig
  generator/src/templates/nginx/http/glue-storefront.server.conf.twig
  generator/src/templates/nginx/http/glue.server.conf.twig
  generator/src/templates/nginx/http/merchant-portal.server.conf.twig
  generator/src/templates/nginx/http/yves.server.conf.twig
  generator/src/templates/nginx/http/zed.server.conf.twig
Labels: bug, ready-for-release

#337 SC-9516: Configure NPM and Node version from deploy.*.yaml
  bin/sdk/images/common.sh
  docs/07-deploy-file/02-deploy.file.reference.v1.md
  generator/deploy-file-generator/config/validation.yml
  generator/deploy-file-generator/src/Validator/Rule/RangeValueRule.php
  generator/index.php
  generator/src/templates/deploy.bash.twig
  images/common/application/Dockerfile.twig
  images/common/cli/Dockerfile
Labels: improvement, ready-for-release

#345 SC-10057: New DockerSDK and DockerCLI logo
  bin/standalone/logo/spryker-cli.sh
  bin/standalone/logo/spryker-sdk-alt1.sh
  bin/standalone/logo/spryker-sdk-alt2.sh
  bin/standalone/logo/spryker-sdk.sh
Labels: merge-only

#308 TE-10998 Replaced static URL sign secret with ENV key
  generator/index.php
Labels: bug, ready-for-release
