Repository spryker/docker-sdk, pull requests merged in 2023-08, with the labels that each got.

#450 SC-13731 SPRYKER_MP_HOST missed or mixed with SPRYKER_BE_HOST into the merchant portal
  generator/src/templates/nginx/http/merchant-portal.server.conf.twig
Labels: bug, ready-for-release

#458 SC-14953: [Github Actions] Failed to get console during docker/sdk up
  .github/workflows/b2b-b2c-demo-shop-tests.yml
  generator/src/templates/deploy.bash.twig
Labels: bug, ready-for-release

#456 SC-13992: Database container doesn't start into the CI
  bin/service/database/mysql.sh
Labels: bug, ready-for-release

#454 SC-13894 Support of Jenkins 2.401
  README.md
  generator/src/templates/service/jenkins/2.401/jenkins.yml.twig
Labels: improvement

#459 SC-14953: Optional services doesn't work without KeyValue service
  generator/deploy-file-generator/config/validation.yml
  generator/index.php
  generator/project-data/src/DataBuilder/ProjectData/Executor/BrokerConnectionsExecutor.php
  generator/project-data/src/DataBuilder/ProjectData/Executor/KeyValueStoreConnectionsExecutor.php
Labels: bug, QA

#460 E2E pipeline has incorrect endpoints list
  generator/src/templates/terraform/e2e/e2e.tf.twig
Labels: bug, ready-for-release
