Repository spryker/docker-sdk, pull requests merged in 2023-06, with the labels that each got.

#446 Custom images for spryker/elasticsearch:7.10 and spryker/opensearch:1.3
  generator/src/templates/service/elastic/7.10/elastic.yml.twig
  generator/src/templates/service/opensearch/1.3/opensearch.yml.twig
Labels: ready-for-release

#447 [SC-13578] Update security repository for Debian into Jenkins service
  images/common/services/jenkins/export/Dockerfile
Labels: ready-for-release

#448 SC-13376: SPRYKER_MP_HOST environment variable is missing in the Jenkins conta…
  generator/src/templates/terraform/store.env.twig
Labels: bug, ready-for-release

#427 Introduced docker/sdk exec command to execute a command for the specific service
  bin/command/compose/exec.sh
  bin/command/compose/ps.sh
  bin/command/compose/up.sh
  bin/sdk/compose.sh
  generator/src/templates/deploy.bash.twig
Labels: improvement, ready-for-release
