Repository spryker/docker-sdk, pull requests merged in 2023-03, with the labels that each got.

#419 service "cli" is not running container #1
  bin/service/database/mysql.sh
Labels: bug

#342 Adjusted prune command to clean up project artefacts
  bin/command/internal/prune.sh
Labels: improvement, ready-for-release

#421 Introduced support of MariaDB 10.6
  README.md
  generator/src/templates/service/mysql/mariadb-10.6/mysql.yml.twig
Labels: improvement, QA

#422 Extended help with `boot` command
  bin/command/install/bootstrap.sh
  bin/command/install/config.sh
Labels: documentation

#423 [SC-12623] [CI] Service `cli` is not running container
  bin/sdk/data/demo.sh
Labels: bug, ready-for-release

#425 Fixed: Gateway container runs regardless CLI containers is not ready yet
  generator/src/templates/nginx/http/gateway/glue.server.conf.twig
  images/common/cli/Dockerfile
Labels: bug, ready-for-release
