Repository spryker/docker-sdk, pull requests merged in 2024-10, with the labels that each got.

#515 FRW-1633 Added support of PostgreSQL v17.
  README.md
  docs/07-deploy-file/02-deploy.file.reference.v1.md
  generator/src/templates/service/postgres/17/postgres.yml.twig
Labels: improvement

#521 CC-34246 Added strict transport security header for the static content.
  generator/src/templates/nginx/http/static.conf.twig
Labels: bug, ready-for-release

#500 Introduce support of the RMQ 3.10 && RMQ 3.11 && RMQ 3.12 && RMQ 3.13
  README.md
  generator/src/templates/service/rabbitmq/3.10/rabbitmq.yml.twig
  generator/src/templates/service/rabbitmq/3.11/rabbitmq.yml.twig
  generator/src/templates/service/rabbitmq/3.12/rabbitmq.yml.twig
  generator/src/templates/service/rabbitmq/3.13/rabbitmq.yml.twig
Labels: ready-for-release, QA Done
